version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - /home/than/Desktop/dockervalue:/var/lib/postgresql/data

  web:
    build: .
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://myuser:mypass@db:5432/mydb
      - DJANGO_SETTINGS_MODULE=your_project_name.settings
    depends_on:
      - db
    volumes:
      - .:/app  # for auto-reload during development
